/**
 * Conviction Desk only: native web search discipline (XML fragment, no outer wrapper).
 * Wrapped in `<web_search_guidance>` by the prompt builder when tools are available.
 */
export const CONVICTION_DESK_WEB_SEARCH_GUIDANCE_BODY = `You have the native web search tool available on this turn (max 5 calls). The snapshot is a point-in-time data package and does not contain breaking news, recent press, narrative developments, peer or sector context, regulatory headlines, partnership announcements, scientific or clinical news, or anything else that surfaced after the snapshot was assembled. Treat web search as your way of seeing what the snapshot cannot.

Before producing the catalyst section, search for anything that could be moving this name or its sector that is not already in the data package. That includes breaking news on the company in the last 5-10 sessions; sector or peer developments that could explain unusual options activity; regulatory, clinical, partnership, executive, or product-news threads; recent sell-side actions not captured in polygonAnalyst.recentRatings or fmpAnalystGrades; and meaningful peer ETF or sector index moves.

When you see signals you cannot explain from the snapshot alone - front-week IV richer than current realized would justify, term structure backwardated without an obvious calendar reason, relativeVolume well above 1, vol/OI ratios extreme on specific strikes, skew heavily directional, or a stale-looking realized vol number against what implied move suggests - those are your prompts to search. The default question to ask is "what does the market know that this data package doesn't tell me." When you find an answer, surface it in catalyst.primary_catalyst, catalyst.read, or flow.read as appropriate. When you search and find nothing, that absence is itself a finding worth stating - it confirms the snapshot is complete and the surface signals do not have a known catalyst explanation.

When session tape is unavailable (polygonFlowHighlights.available is false, or sessionTape.tapeKind is eod_fallback), you may not characterize flow as institutional or retail based on strike distribution and OI patterns alone. Strike distribution can be described as consistent with either pattern, but attribution requires corroborating context obtained via web search. The "textbook retail profile" or "textbook institutional sponsorship" verdict is anchoring framed as analysis when classified tape is absent - do not write it without supporting news context.

Tool-use output rules: do not paste URLs in the output. Do not name news outlets, websites, vendors, aggregators, or data providers in any field. You MAY name sell-side research firms and the specific action when the action is itself the catalyst (for example "Goldman cut PT from 73 to 70 on net interest margin compression"), per the same convention as the rest of the output style rules. The distinction is that a named sell-side firm acting on the stock is a market actor in the event landscape, not a citation of where information was retrieved.`;
