import { Router, type IRouter } from "express";
import authRouter from "./auth";
import marketRouter from "./market";
import aiRouter from "./ai";
import streamRouter from "./stream";
import portfolioRouter from "./portfolio";
import ibRouter from "./ib";
import economicRouter from "./economic";
import secRouter from "./sec";
import pushRouter from "./push";
import journalRouter from "./journal";
import telemetryRouter from "./telemetry";
import scannerRouter from "./scanner";
import scannerUnusualFlowRouter from "./scannerUnusualFlow";
import unusualOptionsRouter from "./unusualOptions";
import snapshotRouter from "./snapshot";
import aiLabRouter from "./aiLab";
import strategistV2Router from "./strategistV2";
const router: IRouter = Router();

router.use("/auth", authRouter);
router.use("/market", marketRouter);
router.use("/ai", aiRouter);
router.use("/stream", streamRouter);
router.use("/portfolio", portfolioRouter);
router.use("/ib", ibRouter);
router.use("/economic", economicRouter);
router.use("/sec", secRouter);
router.use("/push", pushRouter);
router.use("/journal", journalRouter);
router.use("/telemetry", telemetryRouter);
router.use("/scanner", scannerRouter);
router.use("/scanner", scannerUnusualFlowRouter);
router.use("/unusual-options", unusualOptionsRouter);
router.use("/snapshot", snapshotRouter);
router.use("/ai-lab", aiLabRouter);
router.use("/strategist", strategistV2Router);

export default router;
