import { Router, type IRouter } from "express";
import authRouter from "./auth";
import marketRouter from "./market";
import aiRouter from "./ai";
import chatRouter from "./chat";
import streamRouter from "./stream";
import portfolioRouter from "./portfolio";
import ibRouter from "./ib";
import economicRouter from "./economic";
import secRouter from "./sec";
import pushRouter from "./push";
import journalRouter from "./journal";
import telemetryRouter from "./telemetry";
import scannerRouter from "./scanner";
import scannerUnusualFlowRouter from "./scannerUnusualFlow";
import scannerV2Router from "./scannerV2";
import scannerV3Router from "./scannerV3";
import unusualOptionsRouter from "./unusualOptions";
import snapshotRouter from "./snapshot";
import aiLabRouter from "./aiLab";
import strategistCoreRoutes from "./strategistCoreRoutes";
import strategistV2Router from "./strategistV2";
import strategistDiagnosticRouter from "./strategistDiagnostic";
import flowTimeSalesRouter from "./flowTimeSales";
import watchlistsRouter from "./watchlists";
import polygonAnalystRouter from "./polygonAnalyst";
import diagnosticsRouter from "./diagnostics";
import ttsRouter from "./tts";
import adminRouter from "./admin";
import moversRouter from "./movers";
import catalystsRouter from "./catalysts";
import autoTradeRouter from "./autoTrade";
const router: IRouter = Router();

router.use("/auth", authRouter);
router.use("/market", marketRouter);
router.use("/ai", aiRouter);
router.use("/chat", chatRouter);
router.use("/stream", streamRouter);
router.use("/portfolio", portfolioRouter);
router.use("/ib", ibRouter);
router.use("/economic", economicRouter);
router.use("/sec", secRouter);
router.use("/push", pushRouter);
router.use("/journal", journalRouter);
router.use("/telemetry", telemetryRouter);
router.use("/scanner", scannerRouter);
router.use("/scanner", scannerUnusualFlowRouter);
router.use("/scanner", scannerV3Router);
router.use("/v2", scannerV2Router);
router.use("/unusual-options", unusualOptionsRouter);
router.use("/snapshot", snapshotRouter);
router.use("/ai-lab", aiLabRouter);
router.use("/strategist", strategistCoreRoutes);
router.use("/strategist", strategistV2Router);
router.use("/strategist", strategistDiagnosticRouter);
router.use("/flow", flowTimeSalesRouter);
router.use("/watchlists", watchlistsRouter);
router.use("/polygon", polygonAnalystRouter);
router.use("/diagnostics", diagnosticsRouter);
router.use("/tts", ttsRouter);
router.use("/admin", adminRouter);
router.use("/movers", moversRouter);
router.use("/catalysts", catalystsRouter);
router.use("/auto-trade", autoTradeRouter);

export default router;
