// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/scanner-card/Comparison.tsx": () => import("../components/mockups/scanner-card/Comparison.tsx")
};
